version: '3.8'

services:
  postgres:
    image: postgres:latest   
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: secret  
      POSTGRES_DB: mydb  
    ports:
      - "5432:5432"  
    volumes:
     - pgdata:/var/lib/postgresql/data  
    networks:
      - mynetwork  
  adminer:
    image: adminer  
    container_name: my-adminer
    restart: always
    ports:
      - "8080:8080"   
    networks:
      - mynetwork

volumes:
  pgdata:   
networks:
  mynetwork:  